#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.7.1RC1 on Sun Sep 13 19:53:54 2015
#

import wx
from pathlib import Path

# begin wxGlade: dependencies
# end wxGlade
from tune_panel_class import TuningPanel
from search_panel import EditListCtrlPanel
# begin wxGlade: extracode
# end wxGlade


class AorCtrlFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AorCtrlFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.aor_menubar = wx.MenuBar()
        self.mfile = wx.Menu()
        self.aor_menubar.Append(self.mfile, "File")
        self.medit = wx.Menu()
        self.aor_menubar.Append(self.medit, "Edit")
        self.SetMenuBar(self.aor_menubar)
        # Menu Bar end
        self.aor_status = self.CreateStatusBar(1)
        
        # Tool Bar
        self.aor_toolbar = wx.ToolBar(self, -1)
        self.SetToolBar(self.aor_toolbar)
        icon_dir = Path(__file__).resolve().parent / "icons"
        self.aor_toolbar.AddTool(wx.ID_ANY, "newlog", wx.Bitmap(str(icon_dir / "new3.bmp"), wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.aor_toolbar.AddTool(wx.ID_ANY, "open", wx.Bitmap(str(icon_dir / "load3.bmp"), wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.aor_toolbar.AddTool(wx.ID_ANY, "upload", wx.Bitmap(str(icon_dir / "arrow-up_32.bmp"), wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.aor_toolbar.AddTool(wx.ID_ANY, "connect", wx.Bitmap(str(icon_dir / "redo_32.bmp"), wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.aor_toolbar.AddTool(wx.ID_ANY, "config", wx.Bitmap(str(icon_dir / "applications_32.bmp"), wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        # Tool Bar end
        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.rb_vfos = wx.RadioBox(self.panel_1, wx.ID_ANY, "", choices=["VFO-A", "VFO-B", "VFO"], majorDimension=1, style=wx.RA_SPECIFY_COLS)
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.lb_vfa = wx.StaticText(self.panel_3, wx.ID_ANY, "xxxxxxx........", style=wx.ALIGN_RIGHT|wx.ST_NO_AUTORESIZE)
        self.lb_vfb = wx.StaticText(self.panel_3, wx.ID_ANY, "xxxxxxx........", style=wx.ALIGN_RIGHT|wx.ST_NO_AUTORESIZE)
        self.lb_vfo = wx.StaticText(self.panel_3, wx.ID_ANY, "xxxxxxxx........", style=wx.ALIGN_RIGHT|wx.ST_NO_AUTORESIZE)
        self.sizer_12_staticbox = wx.StaticBox(self.panel_3, wx.ID_ANY, "")
        self.sizer_11_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "VFO Frequency [MHz]")
        self.ckbx_auto = wx.CheckBox(self.panel_1, wx.ID_ANY, "A")
        self.sizer_24_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Auto")
        self.cbx_step = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["0.05", "0.1", "0.2", "0.5", "1", "5", "10", "50", "100"], style=wx.CB_DROPDOWN)
        self.sizer_25_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Step")
        self.cbx_mode = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["WFM", "NFM", "SFM", "WAM", "AM", "NAM", "USB", "LSB", "CW"], style=wx.CB_DROPDOWN)
        self.sizer_252_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Mode")
        self.cbx_lists = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["STORED RANGES", "SELECTED CHANNELS", "PASS FREQS", "LOG VIEW", "DATABASE"], style=wx.CB_DROPDOWN)
        self.bt_refresh = wx.Button(self.panel_1, wx.ID_ANY, "Refresh")
        self.sizer_22_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Lists")
        self.ckbx_att = wx.CheckBox(self.panel_1, wx.ID_ANY, "ATT")
        self.ckbx_nl = wx.CheckBox(self.panel_1, wx.ID_ANY, "NL")
        self.ckbx_afc = wx.CheckBox(self.panel_1, wx.ID_ANY, "AFC")
        self.sizer_17_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Options")
        self.tuning_panel = TuningPanel(self.panel_1, wx.ID_ANY)
        self.sizer_5_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Tuning")
        self.operation_panel = wx.Panel(self.panel_1)
        self.operation_panel.SetMinSize((335, 285))
        self.operation_choice = wx.Choice(self.operation_panel, choices=["Stored Channels", "Frequency Range"])
        self.operation_choice.SetSelection(0)
        self.source_choice = wx.Choice(self.operation_panel, choices=["Current Memory Bank", "Linked Memory Banks", "Selected Channels"])
        self.source_choice.SetSelection(0)
        self.memory_source_panel = wx.Panel(self.operation_panel)
        self.memory_bank_choice = wx.Choice(self.memory_source_panel)
        self.scan_source_panel = wx.Panel(self.operation_panel)
        self.cbx_scan = wx.ComboBox(self.scan_source_panel, choices=[str(n) for n in range(10)], style=wx.CB_READONLY)
        self.bt_scgrp = wx.Button(self.scan_source_panel, label="Edit Linked Memory Banks...")
        self.range_source_panel = wx.Panel(self.operation_panel)
        self.range_lower = wx.TextCtrl(self.range_source_panel, size=(95, -1))
        self.range_upper = wx.TextCtrl(self.range_source_panel, size=(95, -1))
        self.range_step = wx.TextCtrl(self.range_source_panel, value="100", size=(95, -1))
        self.range_mode = wx.Choice(self.range_source_panel, choices=["Auto", "WFM", "NFM", "SFM", "WAM", "AM", "NAM", "USB", "LSB", "CW"])
        self.range_mode.SetSelection(0)
        self.bank_source_panel = wx.Panel(self.operation_panel)
        self.search_bank_choice = wx.Choice(self.bank_source_panel)
        for bank in 'ABCDEFGHIJKLMNOPQRSTabcdefghijklmnopqrst':
            self.search_bank_choice.Append(bank, bank)
        self.search_bank_choice.SetSelection(0)
        self.bt_newsearchbank = wx.Button(self.bank_source_panel, label="Create Stored Range...")
        self.bt_editsearchbank = wx.Button(self.bank_source_panel, label="Edit Stored Range...")
        self.search_source_panel = wx.Panel(self.operation_panel)
        self.cbx_search = wx.ComboBox(self.search_source_panel, choices=[str(n) for n in range(10)], style=wx.CB_READONLY)
        self.bt_search = wx.Button(self.search_source_panel, label="Edit Linked Ranges...")
        self.bt_start = wx.Button(self.operation_panel, label="Start")
        self.bt_stop = wx.Button(self.operation_panel, label="Stop")
        self.bt_mkpassfreq = wx.Button(self.panel_1, wx.ID_ANY, "Add Pass Frequency...")
        self.bt_mkpassfreq.Hide()
        self.sql = wx.Slider(self.panel_1, wx.ID_ANY, 0, 0, 255, style=wx.SL_HORIZONTAL)
        self.sql_value = wx.StaticText(self.panel_1, label="---", size=(40, -1))
        self.sizer_18_staticbox = wx.StaticBox(self.panel_1, wx.ID_ANY, "Squelch")
        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.edit_list = EditListCtrlPanel(self)
        # Leave room for the expanded Search section and the existing activity log.
        self.edit_list.SetMinSize((-1, 180))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TOOL, self.log_new, id=wx.ID_ANY)
        self.Bind(wx.EVT_TOOL, self.log_open, id=wx.ID_ANY)
        self.Bind(wx.EVT_TOOL, self.config, id=wx.ID_ANY)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AorCtrlFrame.__set_properties
        self.SetTitle("frame_1")
        self.aor_status.SetStatusWidths([-1])

        # statusbar fields
        aor_status_fields = ["frame_1_statusbar"]
        for i in range(len(aor_status_fields)):
            self.aor_status.SetStatusText(aor_status_fields[i], i)
        self.aor_toolbar.SetToolBitmapSize((32, 32))
        self.aor_toolbar.Realize()
        self.rb_vfos.SetMinSize((78, 100))
        self.rb_vfos.SetSelection(0)
        self.lb_vfa.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lb_vfb.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lb_vfo.SetFont(wx.Font(9, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.panel_3.SetMinSize((195, 100))
        self.cbx_step.SetMinSize((75, 24))
        self.cbx_step.SetSelection(-1)
        self.cbx_mode.SetMinSize((75, 24))
        self.cbx_mode.SetSelection(1)
        self.cbx_lists.SetMinSize((130, 24))
        self.cbx_lists.SetSelection(-1)
        self.bt_refresh.SetMinSize((75, 26))
        self.tuning_panel.SetMinSize((166, 190))
        self.cbx_scan.SetMinSize((65, 24))
        self.cbx_scan.SetSelection(0)
        self.bt_scgrp.SetMinSize((235, 25))
        self.bt_start.SetMinSize((75, 25))
        self.bt_stop.SetMinSize((75, 25))
        self.cbx_search.SetMinSize((65, 24))
        self.cbx_search.SetSelection(0)
        self.bt_search.SetMinSize((235, 25))
        self.bt_mkpassfreq.SetMinSize((155, 25))
        self.sql.SetMinSize((209, 23))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AorCtrlFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_18_staticbox.Lower()
        sizer_18 = wx.StaticBoxSizer(self.sizer_18_staticbox, wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_5_staticbox.Lower()
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.VERTICAL)
        sizer_16 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_17_staticbox.Lower()
        sizer_17 = wx.StaticBoxSizer(self.sizer_17_staticbox, wx.VERTICAL)
        sizer_21 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_22_staticbox.Lower()
        sizer_22 = wx.StaticBoxSizer(self.sizer_22_staticbox, wx.HORIZONTAL)
        sizer_23 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_252_staticbox.Lower()
        sizer_252 = wx.StaticBoxSizer(self.sizer_252_staticbox, wx.HORIZONTAL)
        self.sizer_25_staticbox.Lower()
        sizer_25 = wx.StaticBoxSizer(self.sizer_25_staticbox, wx.HORIZONTAL)
        self.sizer_24_staticbox.Lower()
        sizer_24 = wx.StaticBoxSizer(self.sizer_24_staticbox, wx.HORIZONTAL)
        self.sizer_11_staticbox.Lower()
        sizer_11 = wx.StaticBoxSizer(self.sizer_11_staticbox, wx.HORIZONTAL)
        self.sizer_12_staticbox.Lower()
        sizer_12 = wx.StaticBoxSizer(self.sizer_12_staticbox, wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(self.rb_vfos, 0, wx.BOTTOM | wx.EXPAND | wx.LEFT, 5)
        sizer_13.Add(self.lb_vfa, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_13, 1, wx.EXPAND | wx.RIGHT | wx.TOP, 5)
        sizer_14.Add(self.lb_vfb, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_14, 1, wx.EXPAND | wx.RIGHT, 5)
        sizer_15.Add(self.lb_vfo, 1, wx.EXPAND, 0)
        sizer_12.Add(sizer_15, 1, wx.EXPAND | wx.RIGHT, 5)
        self.panel_3.SetSizer(sizer_12)
        sizer_11.Add(self.panel_3, 1, 0, 0)
        sizer_10.Add(sizer_11, 0, wx.ALL, 5)
        sizer_24.Add(self.ckbx_auto, 0, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.TOP, 4)
        sizer_23.Add(sizer_24, 0, wx.EXPAND, 0)
        sizer_25.Add(self.cbx_step, 0, 0, 0)
        sizer_23.Add(sizer_25, 1, wx.LEFT, 5)
        sizer_252.Add(self.cbx_mode, 0, 0, 0)
        sizer_23.Add(sizer_252, 1, wx.LEFT, 5)
        sizer_21.Add(sizer_23, 0, wx.BOTTOM, 10)
        sizer_22.Add(self.cbx_lists, 0, wx.BOTTOM | wx.TOP, 1)
        sizer_22.Add(self.bt_refresh, 0, wx.BOTTOM | wx.LEFT, 5)
        sizer_21.Add(sizer_22, 0, wx.BOTTOM, 5)
        sizer_16.Add(sizer_21, 0, wx.ALL, 5)
        sizer_17.Add(self.ckbx_att, 0, wx.BOTTOM | wx.TOP, 5)
        sizer_17.Add(self.ckbx_nl, 0, wx.BOTTOM | wx.TOP, 5)
        sizer_17.Add(self.ckbx_afc, 0, wx.TOP, 5)
        sizer_16.Add(sizer_17, 0, wx.ALL | wx.EXPAND, 5)
        sizer_10.Add(sizer_16, 0, 0, 0)
        sizer_2.Add(sizer_10, 0, 0, 0)
        sizer_5.Add(self.tuning_panel, 0, wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(sizer_5, 0, wx.ALL, 3)
        operation_sizer = wx.StaticBoxSizer(wx.VERTICAL, self.operation_panel, "Operation")
        selectors = wx.FlexGridSizer(0, 2, 5, 5)
        for label, control in (("Operation", self.operation_choice), ("Source", self.source_choice)):
            selectors.Add(wx.StaticText(self.operation_panel, label=label), 0, wx.ALIGN_CENTER_VERTICAL)
            selectors.Add(control, 0, wx.EXPAND)
        selectors.AddGrowableCol(1)
        operation_sizer.Add(selectors, 0, wx.EXPAND | wx.ALL, 5)
        memory_sizer = wx.BoxSizer(wx.VERTICAL)
        memory_sizer.Add(wx.StaticText(self.memory_source_panel, label="Memory Bank"), 0, wx.BOTTOM, 3)
        memory_sizer.Add(self.memory_bank_choice, 0, wx.EXPAND)
        self.memory_source_panel.SetSizer(memory_sizer)
        for panel, label, choice, button in ((self.scan_source_panel, "Linked Memory Banks", self.cbx_scan, self.bt_scgrp),
                                             (self.search_source_panel, "Linked Ranges", self.cbx_search, self.bt_search)):
            group_sizer = wx.BoxSizer(wx.VERTICAL)
            group_sizer.Add(wx.StaticText(panel, label=label), 0, wx.BOTTOM, 3)
            row = wx.BoxSizer(wx.HORIZONTAL)
            row.Add(choice, 0)
            row.Add(button, 0, wx.LEFT, 5)
            group_sizer.Add(row)
            panel.SetSizer(group_sizer)
        range_fields = wx.FlexGridSizer(0, 2, 3, 5)
        for label, control in (("Lower MHz", self.range_lower), ("Upper MHz", self.range_upper),
                               ("Step kHz", self.range_step), ("Mode / Auto", self.range_mode)):
            range_fields.Add(wx.StaticText(self.range_source_panel, label=label), 0, wx.ALIGN_CENTER_VERTICAL)
            range_fields.Add(control, 0, wx.EXPAND)
        self.range_source_panel.SetSizer(range_fields)
        bank_sizer = wx.BoxSizer(wx.VERTICAL)
        bank_sizer.Add(wx.StaticText(self.bank_source_panel, label="Stored Range"), 0, wx.BOTTOM, 3)
        bank_sizer.Add(self.search_bank_choice, 0, wx.EXPAND | wx.BOTTOM, 5)
        bank_sizer.Add(self.bt_editsearchbank, 0, wx.EXPAND | wx.BOTTOM, 5)
        bank_sizer.Add(self.bt_newsearchbank, 0, wx.EXPAND)
        self.bank_source_panel.SetSizer(bank_sizer)
        for panel in (self.memory_source_panel, self.scan_source_panel, self.range_source_panel,
                      self.bank_source_panel, self.search_source_panel):
            operation_sizer.Add(panel, 0, wx.EXPAND | wx.ALL, 5)
            panel.Show(panel is self.memory_source_panel)
        operation_sizer.AddStretchSpacer()
        common_buttons = wx.BoxSizer(wx.HORIZONTAL)
        common_buttons.Add(self.bt_start, 1)
        common_buttons.Add(self.bt_stop, 1, wx.LEFT, 5)
        operation_sizer.Add(common_buttons, 0, wx.EXPAND | wx.ALL, 5)
        self.operation_panel.SetSizer(operation_sizer)
        sizer_6.Add(self.operation_panel, 0, wx.EXPAND | wx.ALL, 3)
        sizer_6.Add(self.bt_mkpassfreq, 0, wx.EXPAND | wx.ALL, 3)
        sizer_4.Add(sizer_6, 0, 0, 0)
        sizer_3.Add(sizer_4, 0, wx.EXPAND | wx.LEFT, 0)
        sizer_18.Add(self.sql, 1, wx.BOTTOM | wx.EXPAND, 5)
        sizer_18.Add(self.sql_value, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 5)
        sizer_3.Add(sizer_18, 0, wx.BOTTOM | wx.EXPAND, 5)
        sizer_2.Add(sizer_3, 0, wx.LEFT, 5)
        sizer_2.Add(self.panel_2, 1, 0, 0)
        self.panel_1.SetSizer(sizer_2)
        sizer_1.Add(self.panel_1, 0, wx.EXPAND, 0)
        sizer_1.Add(self.edit_list, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def log_new(self, event):  # wxGlade: AorCtrlFrame.<event_handler>
        print("Event handler 'log_new' not implemented!")
        event.Skip()

    def log_open(self, event):  # wxGlade: AorCtrlFrame.<event_handler>
        print("Event handler 'log_open' not implemented!")
        event.Skip()

    def config(self, event):  # wxGlade: AorCtrlFrame.<event_handler>
        print("Event handler 'config' not implemented!")
        event.Skip()

# end of class AorCtrlFrame
class MyApp(wx.App):
    def OnInit(self):
        aor_ctrl_frame = AorCtrlFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(aor_ctrl_frame)
        aor_ctrl_frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
